name: gmail
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core - BẮT BUỘC
  firebase_core: ^2.27.0  # Cập nhật lên phiên bản mới nhất

  # Các dịch vụ Firebase khác (ví dụ)
  firebase_auth: ^4.19.2 # Cập nhật lên phiên bản mới nhất
  cloud_firestore: ^4.16.0 # Cập nhật lên phiên bản mới nhất
  firebase_storage: ^11.7.2 # Cập nhật lên phiên bản mới nhất
  firebase_messaging: ^14.8.0 # Cập nhật lên phiên bản mới nhất

  # Các gói khác
  # ... (giữ nguyên hoặc cập nhật nếu cần)

  # Gói này bạn có thể để Flutter tự quản lý hoặc cập nhật
  # _flutterfire_internals: # thường không cần khai báo trực tiếp

  # Cập nhật các gói khác nếu chúng cũng cũ
  http: ^1.2.0 # Ví dụ, cập nhật http
  intl: ^0.19.0 # Ví dụ, cập nhật intl

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Cập nhật lints

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  uses-material-design: true
