name: gmail
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0" # SDK này hơi cũ, xem xét nâng cấp lên >=2.19.0 hoặc >=3.0.0 nếu có thể

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2 
  file_picker: ^10.1.9 
  pinput: ^4.0.0 

  shared_preferences: ^2.2.2
  # Các gói khác
  http: ^1.2.0
  intl: ^0.20.2
  firebase_core: ^3.13.1 # Added firebase_core
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_app_check: ^0.3.2+6
  firebase_storage:
  provider: ^6.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Hoặc ^4.0.0 nếu có

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/