name: gmail
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # SDK này hơi cũ, xem xét nâng cấp lên >=2.19.0 hoặc >=3.0.0 nếu có thể

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2 

  # Các gói khác
  http: ^1.2.0
  intl: ^0.19.0
  firebase_core: ^2.24.2 # Added firebase_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Hoặc ^4.0.0 nếu có

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/