// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz_4P5H0GYlmcPLBrzYVuJpHCXTTh3ybw',
    appId: '1:874212207808:ios:a736d2017514cbd53fd125',
    messagingSenderId: '874212207808',
    projectId: 'final-8ec7d',
    storageBucket: 'final-8ec7d.firebasestorage.app',
    iosBundleId: 'com.example.gmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz_4P5H0GYlmcPLBrzYVuJpHCXTTh3ybw',
    appId: '1:874212207808:ios:a736d2017514cbd53fd125',
    messagingSenderId: '874212207808',
    projectId: 'final-8ec7d',
    storageBucket: 'final-8ec7d.firebasestorage.app',
    iosBundleId: 'com.example.gmail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwpb-XDjtIENmGbGlKC5Wt3fj97rjgnN8',
    appId: '1:874212207808:web:982d2c90fb50f98b3fd125',
    messagingSenderId: '874212207808',
    projectId: 'final-8ec7d',
    authDomain: 'final-8ec7d.firebaseapp.com',
    storageBucket: 'final-8ec7d.firebasestorage.app',
    measurementId: 'G-EPFBNHB8TR',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwpb-XDjtIENmGbGlKC5Wt3fj97rjgnN8',
    appId: '1:874212207808:web:982d2c90fb50f98b3fd125',
    messagingSenderId: '874212207808',
    projectId: 'final-8ec7d',
    authDomain: 'final-8ec7d.firebaseapp.com',
    storageBucket: 'final-8ec7d.firebasestorage.app',
    measurementId: 'G-EPFBNHB8TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnCiBLraVyYGMnE1pEXilHWpVqP_VjO0E',
    appId: '1:874212207808:android:4ef476a0a4a182bf3fd125',
    messagingSenderId: '874212207808',
    projectId: 'final-8ec7d',
    storageBucket: 'final-8ec7d.firebasestorage.app',
  );

}