// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB9_ssBAAuB94nAGcN-XzJKBFCCCQb4EQ',
    appId: '1:815388206766:web:673eb5139dc2d6e05c6f3f',
    messagingSenderId: '815388206766',
    projectId: 'flutter-bf15e',
    authDomain: 'flutter-bf15e.firebaseapp.com',
    storageBucket: 'flutter-bf15e.firebasestorage.app',
    measurementId: 'G-92HZC5WZFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcNoDZdFaib70-fbFDzO6tbaHyJQvE2CU',
    appId: '1:815388206766:android:853565734edd47b15c6f3f',
    messagingSenderId: '815388206766',
    projectId: 'flutter-bf15e',
    storageBucket: 'flutter-bf15e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUeMS1-s0cOzIzMjSxWIH3J8FDcEMDVvE',
    appId: '1:815388206766:ios:f8ab976c4bc698205c6f3f',
    messagingSenderId: '815388206766',
    projectId: 'flutter-bf15e',
    storageBucket: 'flutter-bf15e.firebasestorage.app',
    iosBundleId: 'com.example.gmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUeMS1-s0cOzIzMjSxWIH3J8FDcEMDVvE',
    appId: '1:815388206766:ios:f8ab976c4bc698205c6f3f',
    messagingSenderId: '815388206766',
    projectId: 'flutter-bf15e',
    storageBucket: 'flutter-bf15e.firebasestorage.app',
    iosBundleId: 'com.example.gmail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB9_ssBAAuB94nAGcN-XzJKBFCCCQb4EQ',
    appId: '1:815388206766:web:ab79930da4bfc1055c6f3f',
    messagingSenderId: '815388206766',
    projectId: 'flutter-bf15e',
    authDomain: 'flutter-bf15e.firebaseapp.com',
    storageBucket: 'flutter-bf15e.firebasestorage.app',
    measurementId: 'G-5XR4V23WNC',
  );
}
